### Creamos nuevo usuario

POST http://localhost:25060/api/v1/cuenta/
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbWlyYkBnbWFpbC5jb20iLCJyb2xlcyI6WyJBZ3JlZ2FyIGVudHJlbmFtaWVudG9zIl0sImlzcyI6InVjYiIsInJlZnJlc2giOmZhbHNlLCJleHAiOjE2Njk0MzgzMjZ9.lAApnWTs3OeUmrdPWsDpGq69HHnLvUI7OUtWQPmXKLw

{
    "idDeporte": 1,
    "correo": "pepito@gmail.com",
    "contrasenia": "123456789",
    "nombre": "Andres",
    "apellido": "Gomez",
    "numeroTelefono": "123456789"
}


### Datos vacios
POST http://localhost:25060/api/v1/cuenta/
Content-Type: application/json
Accept: application/json
//Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbWFyYWxAZ21haWwuY29tIiwicm9sZXMiOlsidXN1YXJpbyJdLCJpc3MiOiJ1Y2IiLCJyZWZyZXNoIjpmYWxzZSwiZXhwIjoxNjY5MDAwMTU2fQ.v6SSsB_YMMo8_vr81JiCeI1I95vluqm4eQh3RYOjiwc

{
}
### Consultamos el usuario autenticado
GET http://localhost:25060/api/v1/cuenta/
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbWlyYkBnbWFpbC5jb20iLCJyb2xlcyI6WyJBZ3JlZ2FyIGVudHJlbmFtaWVudG9zIl0sImlzcyI6InVjYiIsInJlZnJlc2giOmZhbHNlLCJleHAiOjE2Njk0MzYwMjh9.zhXHlq8qT89akZYuR4_AWMbyrn6YY_Ssanb3tMNR530
