### Creamos nuevo usuario

POST http://localhost:25060/api/v1/cuenta/entrenador/
Content-Type: application/json
Accept: application/json

{
  "idDeporte": null,
  "correo": "entrenador1@gmail.com",
  "contrasenia": "123456789",
  "nombre": "Vladymir",
  "apellido": "Gomez",
  "numeroTelefono": "123456789"
}