### Agregar datos de entrenador
POST http://localhost:25060/api/v1/entrenador/
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlbnRyZW5hZG9yMTJAZ21haWwuY29tIiwicm9sZXMiOlsiQWdyZWdhciBlbnRyZW5hbWllbnRvcyJdLCJpc3MiOiJ1Y2IiLCJyZWZyZXNoIjpmYWxzZSwiZXhwIjoxNjY5OTU4MDA3fQ.8fxPRmULMXCRllPcpPpJVWOd_DZgQywKuBbnP7nNNEU

{
  "idCuenta": 2,
  "fotoEntrenador": "https://cdn.bulbagarden.net/upload/thumb/5/5f/Red_%28anime%29.png/250px-Red_%28anime%29.png",
  "nit": "123456789",
  "correo": "entrenador1@gmail.com"
}