### Datos del lugar de entrenamiento Sucursal
GET http://localhost:25060/api/v1/LugarEntrenamiento/61
### Datos del de clientes del lugar de entrenamiento Sucursal
GET http://localhost:25060/api/v1/LugarEntrenamiento/61/clientes
### Datos de las compras de planes de entrenamiento de un cliente
GET http://localhost:25060/api/v1/LugarEntrenamiento/3/cliente/10
### Datos de los planes de entrenamiento de la sucursal
GET http://localhost:25060/api/v1/LugarEntrenamiento/3/planes
### Insertar un nuevo plan de entrenamiento
POST http://localhost:25060/api/v1/LugarEntrenamiento/plan
Content-Type: application/json
Accept: application/json

{
    "idLugarEntrenamientoSucursal": 2,
    "costo": 7777,
    "cantidadMeses": 10

}

### Insertar datos a una sucursal
POST http://localhost:25060/api/v1/LugarEntrenamiento
Content-Type: application/json
Accept: application/json
Authorization: Bearer

{
  "idCuenta": 1,
  "nombrePropietario": "Juan",
  "apellidoPropietario": "Perez",
  "telefono": "123456789",
  "direccion": "Calle 123"
}