### Datos del Entrenador en la pantalla de inicio
GET http://localhost:25060/api/v1/Entrenador/2
### Datos del de clientes del lugar de entrenamiento Sucursal
GET http://localhost:25060/api/v1/Entrenador/2/clientesActivos
### Datos de las compras de planes del entrenador de un cliente
GET http://localhost:25060/api/v1/Entrenador/2/cliente/10
### Datos de los planes de un entrenador
GET http://localhost:25060/api/v1/Entrenador/2/planes
### Insertar un nuevo plan de entrenamiento
POST http://localhost:25060/api/v1/Entrenador/plan
Content-Type: application/json
Accept: application/json

{
    "idEntrenador": 1,
    "costo": 5000,
    "cantidadMeses": 30

}
###
GET http://localhost:25060/api/v1/cuenta/
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbWlyYkBnbWFpbC5jb20iLCJyb2xlcyI6WyJBZ3JlZ2FyIGVudHJlbmFtaWVudG9zIl0sImlzcyI6InVjYiIsInJlZnJlc2giOmZhbHNlLCJleHAiOjE2Njk3MDY2OTR9.5FcoK32teaT7Bw0UR64kSNQkQsF4ZsRGwL3huTVCYds
