### Creamos tienda

POST http://localhost:25060/api/v1/tienda/
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0aWVuZGExQGdtYWlsLmNvbSIsInJvbGVzIjpbIkFncmVnYXIgdGllbmRhIl0sImlzcyI6InVjYiIsInJlZnJlc2giOmZhbHNlLCJleHAiOjE2Njk5NTYzMzl9.u0Cmr48KW5OkundYrYCsAgSPK_SiaHlUx_hhoSCheuU

{
  "idCuenta": 1,
  "nombreTienda": "Tienda 1",
  "nombrePropietario": "Propietario 1",
  "apellidoPropietario": "Apellido 1",
  "foto": "foto1.jpg",
  "correo": "tienda5@gmail.com",
  "telefono": "123456789",
  "nit": "123456789",
  "direccion": "Calle 1"
}

### Datos vacios
POST http://localhost:25060/api/v1/tienda/
Content-Type: application/json
Accept: application/json

{
}